### PR TITLE
Atmosphère support

### PR DESCRIPTION
**Pull request by ghost**
like in the issue

### CODE REVIEW

**Comment by ThatNerdyPikachu** [comment]
How about explain how to launch a payload?

**Comment by ghost** [comment]
I will think of it

**Comment by ThatNerdyPikachu** [comment]
@Plailect Please close, both you and I know why Thomleg isn't the, er, best person for the job...

**Comment by HylianEternal** [comment]
Gonna have to go with @ThatNerdyPikachu on this one, for rather obvious reasons. @Plailect I'd highly recommend closing this PR ASAP (Get better soon by the way, being sick sucks!).

**Comment by ThatNerdyPikachu** [comment]
Now that I think about it, could Hylian possibly collaborate with you on the Atmosphere guide? He did a awesome job on the wiki, and he is a pretty good person overall~

(Also, yes, get well soon!!)

**Comment by HylianEternal** [comment]
I would be more than willing to lend a helping hand if you'd like. My Discord tag is on my GitHub profile if you wanna DM me.

**Pull request closed without merging**
